apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitops-ansible-operator
  template:
    metadata:
      labels:
        name: gitops-ansible-operator
    spec:
      serviceAccountName: gitops-ansible-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "image-registry.openshift-image-registry.svc:5000/gitops-ansible-operator/gitops-ansible-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "image-registry.openshift-image-registry.svc:5000/gitops-ansible-operator/gitops-ansible-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitops-ansible-operator"
      volumes:
        - name: runner
          emptyDir: {}
